apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1 # server podlarının sayısı
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: "ghcr.io/zeyneperinc/server:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: server-config
            - secretRef:
                name: mongodb-secret
          # resources: # İsteğe bağlı, kaynak kısıtlamaları
          # limits:
          #  memory: "512Mi"
          # cpu: "500m"
          #requests:
          # memory: "256Mi"
          #cpu: "250m"
