---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb_user: {{ .Values.database.mern.user }} # Base64 encoded
  mongodb_password: {{ .Values.database.mern.password }} # Base64 encoded

