apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server
spec:
  type: ClusterIP # Servis tipi: İç ağ (diğer pod'lar için erişim sağlar)
  ports:
    - port: 5001 # Kubernetes içindeki servis portu
      targetPort: 27017 # Container'ın expose ettiği port 5000000001 mi
      protocol: TCP
      #name: http
  selector:
    app: server # Deployment'taki pod'ları seçmek için kullanılan etiket
