# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: server CI

on:
  push:
    branches: [ "main" ]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
    - run: docker build -t ghcr.io/zeyneperinc/server:latest . -f /home/runner/work/mernexample-server/mernexample-server/Dockerfile
    - run: docker push ghcr.io/zeyneperinc/server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name mern-eks-cluster --region ${{ secrets.AWS_REGION }}
  
    - run: helm upgrade -i server -n mern /home/runner/work/mernexample-server/mernexample-server/helm/